### ISSUE TITLE
Config wrong

### ISSUE THREAD

**Issue by franz-josef-kaiser** [Chassis/Tester#1]
After installing `Tester` (running Chassis + SuperCharger), I did the following:

```
cd wp && wp scaffold plugin-tests some-plugin-dir
```

I ran into the problem:

> Error establishing database connection

Searching where the problem could origin from, I looked into `~/wp/local-config-extensions.php` which has the following lines of code, repeating for each extension:

```
if ( file_exists( __DIR__ . '/extensions/tester/local-config.php' ) )
    require_once __DIR__ . '/extensions/tester/local-config.php';
```

_The repeated extensions are (all prepended by `extensions`): `example`, `extensions`, `phpmyadmin` and `tester`)._

So obviously this couldn't work as the file simply does not exist. I then pointed the `tester` extension to the `wpdevel/wp-tests-config.php`, assuming that this was the intended use for having `wpdevel` as submodule. This was resulting in the following:

```
<h1>Your configuration is incomplete.</h1><p>Your <code>content</code> directory doesn't exist. Please either create a content directory or clone <a href='https://github.com/Chassis/SuperCharger" title='SuperCharger'>SuperCharger</a>
```

The first problem which I found in the `wpdevel/wp-tests-config.php` file was the following line right on top:

```
$chassisdir = '/vagrant';
```

There is no `vagrant` subfolder inside the `Chassis/extensions/tester/wpdevel` folder. No matter what I tried from here, it just went through too many files for me to back trace where the problem finally origins from. I hope someone can shed some lights. Thanks.

**Comment by mirzazeyrek** [comment]
Same as @BronsonQuick 

Fatal error: require_once(): Failed opening required '/tmp/wordpress-tests-lib/includes/functions.php' (include_path='.:/usr/share/php') in /vagrant/content/plugins/crawler/tests/bootstrap.php on line 14

also WP_TESTS_DIR returns false.

Just did a fresh install and followed all steps carefully. I am not sure this is on my end or global issue. Could you please check @BronsonQuick @rmccue  ?

Thanks in advance.
