### ISSUE TITLE
Support PHPUnit 6.0

### ISSUE THREAD

**Issue by ntwb** [Chassis/Tester#14]
Via https://phpunit.de/

#### Current Stable Release
• PHPUnit 6.0 is the current stable release series.
• It became stable on February 3, 2017.
• Support for PHPUnit 6 ends February 8, 2019.
• PHPUnit 6.0 is supported on PHP 7.0 and PHP 7.1.

#### Old Stable Release
• PHPUnit 5.7 is the old stable release series.
• It became stable on December 2, 2016.
• Support for PHPUnit 5 ends on February 2, 2018.
• PHPUnit 5.7 is supported on PHP 5.6, PHP 7.0, and PHP 7.1.

####  No Longer Supported
• PHPUnit 4.8 is no longer supported.
• It became stable on August 7, 2015.
• Support for PHPUnit 4 ended on February 3, 2017.
• PHPUnit 4.8 was supported on PHP 5.3 – 5.6.

At a quick glance updating the `if/else` block here is what's needed:
> https://github.com/Chassis/Tester/blob/master/modules/tester/manifests/init.pp#L10-L14

**Comment by BronsonQuick** [comment]
@ntwb Awesome. Thanks for reporting this. You're indeed correct. Updating that block with another condition is all it needs!

**Comment by rmccue** [comment]
I don't think PHPUnit 6 supports WP core unit tests?

**Comment by fklein-lu** [comment]
Correct, PHPUnit 6 does not work with any code not using namespaces: https://github.com/sebastianbergmann/phpunit/wiki/Release-Announcement-for-PHPUnit-6.0.0#backwards-compatibility-issues

**Comment by ntwb** [comment]
Thanks, @fklein-lu & @rmccue 👍
