### ISSUE TITLE
Tester fails to find 

### ISSUE THREAD

**Issue by mirzazeyrek** [Chassis/Tester#30]
Tester fails to find WP_TESTS_DIR.

I think there is a problem with tester extension.

I've carefully followed steps for installation in readme and get this:

Fatal error: require_once(): Failed opening required '/tmp/wordpress-tests-lib/includes/functions.php' (include_path='.:/usr/share/php') in /vagrant/content/plugins/crawler/tests/bootstrap.php on line 13

When I dig a little found out in tests/bootstrap.php : 

getenv('WP_TESTS_DIR') returns false.
so I've added 
$_tests_dir = '/vagrant/extensions/tester/wpdevel/tests/phpunit';

phpunit works as expected:

vagrant@crawler /v/c/p/crawler> phpunit
Installing...
Running as single site... To run multisite, use -c tests/phpunit/multisite.xml
Not running ajax tests. To execute these, use --group ajax.
Not running ms-files tests. To execute these, use --group ms-files.
Not running external-http tests. To execute these, use --group external-http.
PHPUnit 5.7.25 by Sebastian Bergmann and contributors.

.                                                                   1 / 1 (100%)

Time: 2.78 seconds, Memory: 34.00MB

OK (1 test, 1 assertion)

**Comment by BronsonQuick** [comment]
I've only just got around to triaging some issues in this extension. From the looks of your error the error isn't with Tester it's with the bootstrapping code inside the crawler plugin. `/vagrant/content/plugins/crawler/tests/bootstrap.php`
