### ISSUE TITLE
Apparent problems in multisite

### ISSUE THREAD

**Issue by ericnicolaas** [Chassis/Tester#5]
I am running into a problem with running phpunit on a plugin's unit test. I am logged into the Vagrant machine via SSH and simply run `phpunit`. This is the output:

![screen shot 2015-10-23 at 10 52 23 am](https://cloud.githubusercontent.com/assets/676582/10682385/4a400244-7974-11e5-862c-bef03a58bdb0.png)

It seems like all these issues are boiling down the the current blog not being set. I have default domain, path, site ID and blog ID set in the `local-config-db.php` though:

```
define( 'MULTISITE', true );
define( 'SUBDOMAIN_INSTALL', false );
define( 'DOMAIN_CURRENT_SITE', 'charitable-demo.local' );
define( 'PATH_CURRENT_SITE', '/' );
define( 'SITE_ID_CURRENT_SITE', 1 );
define( 'BLOG_ID_CURRENT_SITE', 1 );
```

Anything I'm missing? 

Cheers, 
Eric

**Comment by ericnicolaas** [comment]
Actually, I am getting the same error in a regular WP install (not multisite).

**Comment by BronsonQuick** [comment]
Sorry for the epic delay on this! I am only triaging a few issues now. I think I'd need to have your source code to debug this. I'm guessing you probably don't have that anymore so I'll close this out for now.
